import { AccessRule } from '../../../../src/schema/rbac';

export const ACCESS_POLICY_USER: AccessRule[] = [
  {
    name: 'User: get existing user by username',
    method: 'POST',
    path: '/api/user/get',
    allowedRoles: ['admin', 'user'],
    deniedRoles: ['super_admin'],
    expectedAllowedStatus: 200,
    expectedDeniedStatus: 403,
    jsonBody: { user_name: '$USER_NAME' },
  },
  {
    name: 'User: get non-existing user by username',
    method: 'POST',
    path: '/api/user/get',
    allowedRoles: ['admin', 'user'],
    deniedRoles: ['super_admin'],
    expectedAllowedStatus: 404,
    expectedDeniedStatus: 403,
    jsonBody: { user_name: 'user_that_does_not_exist_qa_12345' },
  },
  {
    name: 'User: get existing user by id',
    method: 'POST',
    path: '/api/user/get_by_id',
    allowedRoles: ['admin', 'user'],
    deniedRoles: ['super_admin'],
    expectedAllowedStatus: 200,
    expectedDeniedStatus: 403,
    jsonBody: { user_id: '$USER_ID' },
  },
  {
    name: 'User: get non-existing user by id',
    method: 'POST',
    path: '/api/user/get_by_id',
    allowedRoles: ['admin', 'user'],
    deniedRoles: ['super_admin'],
    expectedAllowedStatus: 404,
    expectedDeniedStatus: 403,
    jsonBody: { user_id: '000000000000000000000000' },
  },
  {
    name: 'User: get all users',
    method: 'POST',
    path: '/api/user/get_all',
    allowedRoles: ['admin', 'super_admin'],
    deniedRoles: ['user'],
    expectedAllowedStatus: 200,
    expectedDeniedStatus: 403,
    jsonBody: {},
  },
  {
    name: 'User: get system roles',
    method: 'POST',
    path: '/api/user/get_roles',
    allowedRoles: ['admin', 'user'],
    deniedRoles: ['super_admin'],
    expectedAllowedStatus: 200,
    expectedDeniedStatus: 403,
    jsonBody: {},
  },
  {
    name: 'User: update non-existing user',
    method: 'POST',
    path: '/api/user/update',
    allowedRoles: ['admin', 'user'],
    deniedRoles: ['super_admin'],
    expectedAllowedStatus: 404,
    expectedDeniedStatus: 403,
    data: { user_id: '000000000000000000000000', first_name: 'RBAC' },
  },
  {
    name: 'User: create with invalid email',
    method: 'POST',
    path: '/api/user/create',
    allowedRoles: ['admin', 'super_admin'],
    deniedRoles: ['user'],
    expectedAllowedStatus: 422,
    expectedDeniedStatus: 403,
    data: {
      org_name: '$ORG_NAME',
      user_name: 'rbac-create-check',
      first_name: 'RBAC',
      last_name: 'Check',
      role_id: '$USER_ROLE_ID',
      email: 'invalid-email',
    },
  },
  {
    name: 'User: delete non-existing user',
    method: 'POST',
    path: '/api/user/delete',
    allowedRoles: ['admin', 'super_admin'],
    deniedRoles: ['user'],
    expectedAllowedStatus: 404,
    expectedDeniedStatus: 403,
    jsonBody: { user_id: '000000000000000000000000' },
  },
  {
    name: 'User: unlock non-existing user',
    method: 'POST',
    path: '/api/user/unlock_user',
    allowedRoles: ['admin', 'super_admin'],
    deniedRoles: ['user'],
    expectedAllowedStatus: 404,
    expectedDeniedStatus: 403,
    jsonBody: { username: 'nonexistent_user_qa_12345' },
  },
  {
    name: 'User: reset MFA for non-existing user',
    method: 'POST',
    path: '/api/user/reset_user_mfa',
    allowedRoles: ['admin', 'super_admin'],
    deniedRoles: ['user'],
    expectedAllowedStatus: 404,
    expectedDeniedStatus: 403,
    jsonBody: { user_id: '000000000000000000000000' },
  },
];
